[package]
name = "rmp"
version = "0.8.7"
authors = ["Evgeny Safronov <division494@gmail.com>"]
license = "MIT"
description = "Pure Rust MessagePack serialization implementation"
repository = "https://github.com/3Hren/msgpack-rust"
documentation = "https://docs.rs/rmp"
readme = "README.md"
keywords = ["msgpack", "MessagePack"]
categories = ["encoding"]

[dependencies]
byteorder = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.0" }
num-traits = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.0" }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.0" }


[dev-dependencies]
quickcheck = "0.3"
